INSERT INTO n8n_files (filename, file_path, file_extension, file_size, is_directory) VALUES
('calendar_event_auto-tag.json', '/Users/tushar/Desktop/N8N-Agents/n8n/calendar_event_auto-tag.json', '.json', 7620, false),
('grant_application_routing.json', '/Users/tushar/Desktop/N8N-Agents/n8n/grant_application_routing.json', '.json', 7638, false),
('Simple Expense Tracker with n8n Chat, AI Agent and Google Sheets.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Simple Expense Tracker with n8n Chat, AI Agent and Google Sheets.txt', '.txt', 7812, false),
('AI-Generated Summary Block for WordPress Posts.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI-Generated Summary Block for WordPress Posts.txt', '.txt', 34600, false),
('Zoom AI Meeting Assistant creates mail summary, ClickUp tasks and follow-up call.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Zoom AI Meeting Assistant creates mail summary, ClickUp tasks and follow-up call.txt', '.txt', 20578, false),
('auto-dm_new_twitter_followers.json', '/Users/tushar/Desktop/N8N-Agents/n8n/auto-dm_new_twitter_followers.json', '.json', 7830, false),
('Automatic Background Removal for Images in Google Drive.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automatic Background Removal for Images in Google Drive.txt', '.txt', 10984, false),
('AI-Powered Candidate Shortlisting Automation for ERPNext.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI-Powered Candidate Shortlisting Automation for ERPNext.txt', '.txt', 24251, false),
('Chat with PDF docs using AI (quoting sources).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Chat with PDF docs using AI (quoting sources).txt', '.txt', 11643, false),
('Send a ChatGPT email reply and save responses to Google Sheets.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Send a ChatGPT email reply and save responses to Google Sheets.txt', '.txt', 74895, false),
('idea_to_ig_carousel.json', '/Users/tushar/Desktop/N8N-Agents/n8n/idea_to_ig_carousel.json', '.json', 7596, false),
('Chat with a Google Sheet using AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Chat with a Google Sheet using AI.txt', '.txt', 11040, false),
('public_form_auto_triage.json', '/Users/tushar/Desktop/N8N-Agents/n8n/public_form_auto_triage.json', '.json', 7628, false),
('Telegram AI Bot_ NeurochainAI Text & Image - NeurochainAI Basic API Integration.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Telegram AI Bot_ NeurochainAI Text & Image - NeurochainAI Basic API Integration.txt', '.txt', 19739, false),
('Use AI to organize your Todoist Inbox.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Use AI to organize your Todoist Inbox.txt', '.txt', 5799, false),
('api_stats_chart.json', '/Users/tushar/Desktop/N8N-Agents/n8n/api_stats_chart.json', '.json', 7828, false),
('Monthly Spotify Track Archiving and Playlist Classification.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Monthly Spotify Track Archiving and Playlist Classification.txt', '.txt', 41883, false),
('create e-mail responses with fastmail and OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/create e-mail responses with fastmail and OpenAI.txt', '.txt', 10760, false),
('car_insurance_quote_generator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/car_insurance_quote_generator.json', '.json', 6050, false),
('morning_briefing_email.json', '/Users/tushar/Desktop/N8N-Agents/n8n/morning_briefing_email.json', '.json', 7619, false),
('follow-up_emails.json', '/Users/tushar/Desktop/N8N-Agents/n8n/follow-up_emails.json', '.json', 7446, false),
('Summarize Google Sheets form feedback via OpenAI_s GPT-4.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Summarize Google Sheets form feedback via OpenAI_s GPT-4.txt', '.txt', 6791, false),
('OpenAI-powered tweet generator.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/OpenAI-powered tweet generator.txt', '.txt', 2264, false),
('Suggest meeting slots using AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Suggest meeting slots using AI.txt', '.txt', 10997, false),
('customer_auto-tagging.json', '/Users/tushar/Desktop/N8N-Agents/n8n/customer_auto-tagging.json', '.json', 7878, false),
('Email Summary Agent.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Email Summary Agent.txt', '.txt', 9257, false),
('Analyze Suspicious Email Contents with ChatGPT Vision.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Analyze Suspicious Email Contents with ChatGPT Vision.txt', '.txt', 14315, false),
('tenant_screening_summary.json', '/Users/tushar/Desktop/N8N-Agents/n8n/tenant_screening_summary.json', '.json', 6004, false),
('transaction_logs_backup.json', '/Users/tushar/Desktop/N8N-Agents/n8n/transaction_logs_backup.json', '.json', 7486, false),
('Supabase Insertion & Upsertion & Retrieval.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Supabase Insertion & Upsertion & Retrieval.txt', '.txt', 11389, false),
('RAG_Context-Aware Chunking _ Google Drive to Pinecone via OpenRouter & Gemini.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/RAG_Context-Aware Chunking _ Google Drive to Pinecone via OpenRouter & Gemini.txt', '.txt', 8957, false),
('Automate LinkedIn Outreach with Notion and OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automate LinkedIn Outreach with Notion and OpenAI.txt', '.txt', 6722, false),
('Query n8n Credentials with AI SQL Agent.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Query n8n Credentials with AI SQL Agent.txt', '.txt', 7821, false),
('Update Twitter banner using HTTP request.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Update Twitter banner using HTTP request.txt', '.txt', 1339, false),
('AI Agent for realtime insights on meetings.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Agent for realtime insights on meetings.txt', '.txt', 17217, false),
('Extract license plate number from image uploaded via an n8n form.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Extract license plate number from image uploaded via an n8n form.txt', '.txt', 3156, false),
('AI agent for Instagram DM_inbox. Manychat + Open AI integration.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI agent for Instagram DM_inbox. Manychat + Open AI integration.txt', '.txt', 6028, false),
('Chat with your event schedule from Google Sheets in Telegram.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Chat with your event schedule from Google Sheets in Telegram.txt', '.txt', 12700, false),
('grid_load_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/grid_load_alert.json', '.json', 5969, false),
('Easy Image Captioning with Gemini 1.5 Pro.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Easy Image Captioning with Gemini 1.5 Pro.txt', '.txt', 10162, false),
('Force AI to use a specific output format.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Force AI to use a specific output format.txt', '.txt', 4509, false),
('IT Ops AI SlackBot Workflow - Chat with your knowledge base.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/IT Ops AI SlackBot Workflow - Chat with your knowledge base.txt', '.txt', 16494, false),
('Analyze feedback using AWS Comprehend and send it to a Mattermost channel.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Analyze feedback using AWS Comprehend and send it to a Mattermost channel.txt', '.txt', 1811, false),
('Invoice data extraction with LlamaParse and OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Invoice data extraction with LlamaParse and OpenAI.txt', '.txt', 22067, false),
('Generate Instagram Content from Top Trends with AI Image Generation.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Generate Instagram Content from Top Trends with AI Image Generation.txt', '.txt', 29271, false),
('AI-Powered Social Media Amplifier.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI-Powered Social Media Amplifier.txt', '.txt', 25469, false),
('Sentiment Analysis Tracking on Support Issues with Linear and Slack.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Sentiment Analysis Tracking on Support Issues with Linear and Slack.txt', '.txt', 17943, false),
('AI-Powered Email Automation for Business_ Summarize & Respond with RAG.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI-Powered Email Automation for Business_ Summarize & Respond with RAG.txt', '.txt', 23659, false),
('Upload to Instagram and Tiktok from Google Drive.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Upload to Instagram and Tiktok from Google Drive.txt', '.txt', 10277, false),
('commodity_price_tracker.json', '/Users/tushar/Desktop/N8N-Agents/n8n/commodity_price_tracker.json', '.json', 5982, false),
('Siri AI Agent_ Apple Shortcuts powered voice template.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Siri AI Agent_ Apple Shortcuts powered voice template.txt', '.txt', 4868, false),
('open_house_reminder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/open_house_reminder.json', '.json', 5977, false),
('in‑game_event_reminder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/in‑game_event_reminder.json', '.json', 6029, false),
('Detect hallucinations using specialised Ollama model bespoke-minicheck.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Detect hallucinations using specialised Ollama model bespoke-minicheck.txt', '.txt', 13099, false),
('weather_packing_list_generator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/weather_packing_list_generator.json', '.json', 6044, false),
('content_idea_brainstormer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/content_idea_brainstormer.json', '.json', 5992, false),
('Configure your own Image Creation API Using OpenAI DALLE-3.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Configure your own Image Creation API Using OpenAI DALLE-3.txt', '.txt', 3061, false),
('Automate SIEM Alert Enrichment with MITRE ATT&CK, Qdrant & Zendesk in n8n.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automate SIEM Alert Enrichment with MITRE ATT&CK, Qdrant & Zendesk in n8n.txt', '.txt', 18190, false),
('airport_lounge_finder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/airport_lounge_finder.json', '.json', 5962, false),
('environmental_data_dashboard.json', '/Users/tushar/Desktop/N8N-Agents/n8n/environmental_data_dashboard.json', '.json', 6022, false),
('Automate Your RFP Process with OpenAI Assistants.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automate Your RFP Process with OpenAI Assistants.txt', '.txt', 14297, false),
('ad_campaign_performance_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/ad_campaign_performance_alert.json', '.json', 6027, false),
('Analyze feedback and send a message on Mattermost.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Analyze feedback and send a message on Mattermost.txt', '.txt', 2066, false),
('.DS_Store', '/Users/tushar/Desktop/N8N-Agents/n8n/.DS_Store', '', 6148, false),
('rental_price_estimator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/rental_price_estimator.json', '.json', 6004, false),
('product_description_generator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/product_description_generator.json', '.json', 7842, false),
('Send Google analytics data to A.I. to analyze then save results in Baserow.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Send Google analytics data to A.I. to analyze then save results in Baserow.txt', '.txt', 24195, false),
('pr_crisis_detector.json', '/Users/tushar/Desktop/N8N-Agents/n8n/pr_crisis_detector.json', '.json', 5947, false),
('Ask questions about a PDF using AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Ask questions about a PDF using AI.txt', '.txt', 7340, false),
('Create a Branded AI-Powered Website Chatbot.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Create a Branded AI-Powered Website Chatbot.txt', '.txt', 27600, false),
('Telegram chat with PDF.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Telegram chat with PDF.txt', '.txt', 10228, false),
('order_shipped_notification.json', '/Users/tushar/Desktop/N8N-Agents/n8n/order_shipped_notification.json', '.json', 7659, false),
('🤖🧠 AI Agent Chatbot + LONG TERM Memory + Note Storage + Telegram.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/🤖🧠 AI Agent Chatbot + LONG TERM Memory + Note Storage + Telegram.txt', '.txt', 12986, false),
('AI Agent to chat with Airtable and analyze data.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Agent to chat with Airtable and analyze data.txt', '.txt', 33388, false),
('Automate Image Validation Tasks using AI Vision.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automate Image Validation Tasks using AI Vision.txt', '.txt', 8817, false),
('Convert URL HTML to Markdown Format and Get Page Links.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Convert URL HTML to Markdown Format and Get Page Links.txt', '.txt', 9246, false),
('applicant_feedback_folder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/applicant_feedback_folder.json', '.json', 7938, false),
('Build a Financial Documents Assistant using Qdrant and Mistral.ai.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Build a Financial Documents Assistant using Qdrant and Mistral.ai.txt', '.txt', 19038, false),
('Summarize SERPBear data with AI (via Openrouter) and save it to Baserow.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Summarize SERPBear data with AI (via Openrouter) and save it to Baserow.txt', '.txt', 7046, false),
('ble_beacon_mapper.json', '/Users/tushar/Desktop/N8N-Agents/n8n/ble_beacon_mapper.json', '.json', 5978, false),
('quiz_auto_grader.json', '/Users/tushar/Desktop/N8N-Agents/n8n/quiz_auto_grader.json', '.json', 7823, false),
('Extract insights & analyse YouTube comments via AI Agent chat.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Extract insights & analyse YouTube comments via AI Agent chat.txt', '.txt', 28091, false),
('Detect toxic language in Telegram messages.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Detect toxic language in Telegram messages.txt', '.txt', 2150, false),
('monthly_social_media_report.json', '/Users/tushar/Desktop/N8N-Agents/n8n/monthly_social_media_report.json', '.json', 7534, false),
('Respond to WhatsApp Messages with AI Like a Pro!.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Respond to WhatsApp Messages with AI Like a Pro!.txt', '.txt', 21746, false),
('log_twitter_mentions_in_notion.json', '/Users/tushar/Desktop/N8N-Agents/n8n/log_twitter_mentions_in_notion.json', '.json', 7554, false),
('Prepare CSV files with GPT-4Prepare CSV files with GPT-4.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Prepare CSV files with GPT-4Prepare CSV files with GPT-4.txt', '.txt', 10039, false),
('Author and Publish Blog Posts From Google Sheets.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Author and Publish Blog Posts From Google Sheets.txt', '.txt', 36265, false),
('Make OpenAI Citation for File Retrieval RAG.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Make OpenAI Citation for File Retrieval RAG.txt', '.txt', 10834, false),
('Daily meetings summarization with Gemini AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Daily meetings summarization with Gemini AI.txt', '.txt', 5172, false),
('AI Automated HR Workflow for CV Analysis and Candidate Evaluation.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Automated HR Workflow for CV Analysis and Candidate Evaluation.txt', '.txt', 14438, false),
('birthday_telegram_reminder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/birthday_telegram_reminder.json', '.json', 7647, false),
('ev_charging_station_locator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/ev_charging_station_locator.json', '.json', 6040, false),
('lemlist __ GPT-3_ Supercharge your sales workflows.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/lemlist __ GPT-3_ Supercharge your sales workflows.txt', '.txt', 7024, false),
('Analyze tradingview.com charts with Chrome extension, N8N and OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Analyze tradingview.com charts with Chrome extension, N8N and OpenAI.txt', '.txt', 2990, false),
('customer_sentiment_analysis.json', '/Users/tushar/Desktop/N8N-Agents/n8n/customer_sentiment_analysis.json', '.json', 7822, false),
('drone_image_crop_health.json', '/Users/tushar/Desktop/N8N-Agents/n8n/drone_image_crop_health.json', '.json', 6009, false),
('Automate Content Generator for WordPress with DeepSeek R1.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automate Content Generator for WordPress with DeepSeek R1.txt', '.txt', 12277, false),
('mailchimp_campaign_tracking.json', '/Users/tushar/Desktop/N8N-Agents/n8n/mailchimp_campaign_tracking.json', '.json', 7534, false),
('calendar_to_clickup.json', '/Users/tushar/Desktop/N8N-Agents/n8n/calendar_to_clickup.json', '.json', 7860, false),
('price_update_google_sheet.json', '/Users/tushar/Desktop/N8N-Agents/n8n/price_update_google_sheet.json', '.json', 7634, false),
('abandoned_cart_email.json', '/Users/tushar/Desktop/N8N-Agents/n8n/abandoned_cart_email.json', '.json', 7589, false),
('csv_attachment_to_airtable.json', '/Users/tushar/Desktop/N8N-Agents/n8n/csv_attachment_to_airtable.json', '.json', 7945, false),
('Automate Blog Creation in Brand Voice with AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automate Blog Creation in Brand Voice with AI.txt', '.txt', 17085, false),
('podcast_show_notes_generator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/podcast_show_notes_generator.json', '.json', 6022, false),
('Write a WordPress post with AI (starting from a few keywords).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Write a WordPress post with AI (starting from a few keywords).txt', '.txt', 22040, false),
('WordPress - AI Chatbot to enhance user experience - with Supabase and OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/WordPress - AI Chatbot to enhance user experience - with Supabase and OpenAI.txt', '.txt', 33890, false),
('Telegram AI bot assistant_ ready-made template for voice & text messages.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Telegram AI bot assistant_ ready-made template for voice & text messages.txt', '.txt', 11167, false),
('Notion to Pinecone Vector Store Integration.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Notion to Pinecone Vector Store Integration.txt', '.txt', 5467, false),
('AI Agent To Chat With Files In Supabase Storage.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Agent To Chat With Files In Supabase Storage.txt', '.txt', 17910, false),
('Automate testimonials in Strapi with n8n.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automate testimonials in Strapi with n8n.txt', '.txt', 6310, false),
('Gmail AI Auto-Responder_ Create Draft Replies to incoming emails.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Gmail AI Auto-Responder_ Create Draft Replies to incoming emails.txt', '.txt', 6952, false),
('sendgrid_bounce_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/sendgrid_bounce_alert.json', '.json', 7486, false),
('lead_to_hubspot.json', '/Users/tushar/Desktop/N8N-Agents/n8n/lead_to_hubspot.json', '.json', 7434, false),
('Automated End-to-End Fine-Tuning of OpenAI Models with Google Drive Integration.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automated End-to-End Fine-Tuning of OpenAI Models with Google Drive Integration.txt', '.txt', 5709, false),
('blood_test_email_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/blood_test_email_alert.json', '.json', 7623, false),
('Vector Database as a Big Data Analysis Tool for AI Agents [1_3 anomaly][1_2 KNN].txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Vector Database as a Big Data Analysis Tool for AI Agents [1_3 anomaly][1_2 KNN].txt', '.txt', 18757, false),
('Build a Tax Code Assistant with Qdrant, Mistral.ai and OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Build a Tax Code Assistant with Qdrant, Mistral.ai and OpenAI.txt', '.txt', 23251, false),
('AI-Powered RAG Workflow For Stock Earnings Report Analysis.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI-Powered RAG Workflow For Stock Earnings Report Analysis.txt', '.txt', 17500, false),
('Customer Support Channel and Ticketing System with Slack and Linear.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Customer Support Channel and Ticketing System with Slack and Linear.txt', '.txt', 11640, false),
('loot‑box_probability_calculator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/loot‑box_probability_calculator.json', '.json', 6062, false),
('Create dynamic Twitter profile banner.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Create dynamic Twitter profile banner.txt', '.txt', 5015, false),
('AI chatbot that can search the web.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI chatbot that can search the web.txt', '.txt', 3079, false),
('auto-post_blogs_to_linkedin_and_twitter.json', '/Users/tushar/Desktop/N8N-Agents/n8n/auto-post_blogs_to_linkedin_and_twitter.json', '.json', 7630, false),
('AI_ Ask questions about any data source (using the n8n workflow retriever).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI_ Ask questions about any data source (using the n8n workflow retriever).txt', '.txt', 2981, false),
('Generate Text-to-Speech Using Elevenlabs via API.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Generate Text-to-Speech Using Elevenlabs via API.txt', '.txt', 3927, false),
('Summarize your emails with A.I. (via Openrouter) and send to Line messenger (1).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Summarize your emails with A.I. (via Openrouter) and send to Line messenger (1).txt', '.txt', 4976, false),
('machine_downtime_predictor.json', '/Users/tushar/Desktop/N8N-Agents/n8n/machine_downtime_predictor.json', '.json', 6024, false),
('Create, update, and get a profile in Humantic AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Create, update, and get a profile in Humantic AI.txt', '.txt', 1788, false),
('currency_exchange_estimator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/currency_exchange_estimator.json', '.json', 6030, false),
('road_trip_stop_planner.json', '/Users/tushar/Desktop/N8N-Agents/n8n/road_trip_stop_planner.json', '.json', 6004, false),
('Chat with OpenAIs GPT via a simple Telegram Bot.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Chat with OpenAIs GPT via a simple Telegram Bot.txt', '.txt', 1924, false),
('predictive_maintenance_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/predictive_maintenance_alert.json', '.json', 6022, false),
('cron_success_slack.json', '/Users/tushar/Desktop/N8N-Agents/n8n/cron_success_slack.json', '.json', 7587, false),
('Building RAG Chatbot for Movie Recommendations with Qdrant and Open AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Building RAG Chatbot for Movie Recommendations with Qdrant and Open AI.txt', '.txt', 15163, false),
('recall_notice_tracker.json', '/Users/tushar/Desktop/N8N-Agents/n8n/recall_notice_tracker.json', '.json', 5999, false),
('Notion knowledge base AI assistant.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Notion knowledge base AI assistant.txt', '.txt', 10276, false),
('live_stream_chat_moderator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/live_stream_chat_moderator.json', '.json', 6024, false),
('image_captioning.json', '/Users/tushar/Desktop/N8N-Agents/n8n/image_captioning.json', '.json', 7446, false),
('irrigation_schedule_optimizer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/irrigation_schedule_optimizer.json', '.json', 6029, false),
('Automated Hugging Face Paper Summary Fetching & Categorization Workflow.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automated Hugging Face Paper Summary Fetching & Categorization Workflow.txt', '.txt', 12452, false),
('power_outage_sms.json', '/Users/tushar/Desktop/N8N-Agents/n8n/power_outage_sms.json', '.json', 5962, false),
('Conversational Interviews with AI Agents and n8n Forms.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Conversational Interviews with AI Agents and n8n Forms.txt', '.txt', 40263, false),
('Add positive feedback messages to a table in Notion.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Add positive feedback messages to a table in Notion.txt', '.txt', 2873, false),
('Using External Workflows as Tools in n8n.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Using External Workflows as Tools in n8n.txt', '.txt', 2462, false),
('Flux Dev Image Generation (Fal.ai) to Google Drive.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Flux Dev Image Generation (Fal.ai) to Google Drive.txt', '.txt', 6668, false),
('Text automations using Apple Shortcuts.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Text automations using Apple Shortcuts.txt', '.txt', 10110, false),
('Personal Shopper Chatbot for WooCommerce with RAG using Google Drive and openAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Personal Shopper Chatbot for WooCommerce with RAG using Google Drive and openAI.txt', '.txt', 14398, false),
('CV Screening with OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/CV Screening with OpenAI.txt', '.txt', 12323, false),
('lead_scoring_with_mls_data.json', '/Users/tushar/Desktop/N8N-Agents/n8n/lead_scoring_with_mls_data.json', '.json', 6014, false),
('Chat with GitHub API Documentation_ RAG-Powered Chatbot with Pinecone & OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Chat with GitHub API Documentation_ RAG-Powered Chatbot with Pinecone & OpenAI.txt', '.txt', 8239, false),
('Modular & Customizable AI-Powered Email Routing_ Text Classifier for eCommerce.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Modular & Customizable AI-Powered Email Routing_ Text Classifier for eCommerce.txt', '.txt', 18495, false),
('weekly_notes_backup.json', '/Users/tushar/Desktop/N8N-Agents/n8n/weekly_notes_backup.json', '.json', 7580, false),
('product_launch_email.json', '/Users/tushar/Desktop/N8N-Agents/n8n/product_launch_email.json', '.json', 7462, false),
('Transform Image to Lego Style Using Line and Dall-E.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Transform Image to Lego Style Using Line and Dall-E.txt', '.txt', 3535, false),
('ETL pipeline for text processing.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/ETL pipeline for text processing.txt', '.txt', 3285, false),
('ocr_receipts_to_notion.json', '/Users/tushar/Desktop/N8N-Agents/n8n/ocr_receipts_to_notion.json', '.json', 7494, false),
('daily_content_ideas.json', '/Users/tushar/Desktop/N8N-Agents/n8n/daily_content_ideas.json', '.json', 7454, false),
('Open Deep Research - AI-Powered Autonomous Research Workflow.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Open Deep Research - AI-Powered Autonomous Research Workflow.txt', '.txt', 10743, false),
('toggl_daily_report.json', '/Users/tushar/Desktop/N8N-Agents/n8n/toggl_daily_report.json', '.json', 7857, false),
('carbon_footprint_estimator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/carbon_footprint_estimator.json', '.json', 6024, false),
('Scrape and summarize posts of a news site without RSS feed using AI and save them to a NocoDB.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Scrape and summarize posts of a news site without RSS feed using AI and save them to a NocoDB.txt', '.txt', 17766, false),
('forward_attachments.json', '/Users/tushar/Desktop/N8N-Agents/n8n/forward_attachments.json', '.json', 7734, false),
('translate_form_submissions.json', '/Users/tushar/Desktop/N8N-Agents/n8n/translate_form_submissions.json', '.json', 7514, false),
('Send a random recipe once a day to Telegram.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Send a random recipe once a day to Telegram.txt', '.txt', 7363, false),
('Screen Applicants With AI, notify HR and save them in a Google Sheet.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Screen Applicants With AI, notify HR and save them in a Google Sheet.txt', '.txt', 8678, false),
('Automate Screenshots with URLbox & Analyze them with AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automate Screenshots with URLbox & Analyze them with AI.txt', '.txt', 4366, false),
('compliance_checklist_builder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/compliance_checklist_builder.json', '.json', 6024, false),
('Dynamically generate a webpage from user request using OpenAI Structured Output.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Dynamically generate a webpage from user request using OpenAI Structured Output.txt', '.txt', 7929, false),
('Qualify replies from Pipedrive persons with AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Qualify replies from Pipedrive persons with AI.txt', '.txt', 6288, false),
('monthly_expense_report.json', '/Users/tushar/Desktop/N8N-Agents/n8n/monthly_expense_report.json', '.json', 7494, false),
('iot_device_firmware_update_planner.json', '/Users/tushar/Desktop/N8N-Agents/n8n/iot_device_firmware_update_planner.json', '.json', 6063, false),
('Autonomous AI crawler.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Autonomous AI crawler.txt', '.txt', 28621, false),
('AI Agent _ Google calendar assistant using OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Agent _ Google calendar assistant using OpenAI.txt', '.txt', 11965, false),
('Talk to your SQLite database with a LangChain AI Agent.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Talk to your SQLite database with a LangChain AI Agent.txt', '.txt', 5713, false),
('Analyse papers from Hugging Face with AI and store them in Notion.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Analyse papers from Hugging Face with AI and store them in Notion.txt', '.txt', 9419, false),
('music_playlist_mood_tagger.json', '/Users/tushar/Desktop/N8N-Agents/n8n/music_playlist_mood_tagger.json', '.json', 5985, false),
('mortgage_rate_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/mortgage_rate_alert.json', '.json', 5979, false),
('Vector Database as a Big Data Analysis Tool for AI Agents [2_2 KNN].txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Vector Database as a Big Data Analysis Tool for AI Agents [2_2 KNN].txt', '.txt', 13098, false),
('Breakdown Documents into Study Notes using Templating MistralAI and Qdrant.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Breakdown Documents into Study Notes using Templating MistralAI and Qdrant.txt', '.txt', 24212, false),
('Effortless Email Management with AI-Powered Summarization & Review.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Effortless Email Management with AI-Powered Summarization & Review.txt', '.txt', 16999, false),
('Custom LangChain agent written in JavaScript.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Custom LangChain agent written in JavaScript.txt', '.txt', 4524, false),
('Extract and process information directly from PDF using Claude and Gemini.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Extract and process information directly from PDF using Claude and Gemini.txt', '.txt', 7199, false),
('notion_api_update.json', '/Users/tushar/Desktop/N8N-Agents/n8n/notion_api_update.json', '.json', 7578, false),
('battery_health_monitor.json', '/Users/tushar/Desktop/N8N-Agents/n8n/battery_health_monitor.json', '.json', 5978, false),
('Twitter Virtual AI Influencer.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Twitter Virtual AI Influencer.txt', '.txt', 6769, false),
('KB Tool - Confluence Knowledge Base.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/KB Tool - Confluence Knowledge Base.txt', '.txt', 5845, false),
('game_bug_triage.json', '/Users/tushar/Desktop/N8N-Agents/n8n/game_bug_triage.json', '.json', 5932, false),
('AI Customer feedback sentiment analysis.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Customer feedback sentiment analysis.txt', '.txt', 6590, false),
('Chat with Postgresql Database.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Chat with Postgresql Database.txt', '.txt', 7006, false),
('AI Voice Chat using Webhook, Memory Manager, OpenAI, Google Gemini & ElevenLabs.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Voice Chat using Webhook, Memory Manager, OpenAI, Google Gemini & ElevenLabs.txt', '.txt', 8267, false),
('Generating Image Embeddings via Textual Summarisation.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Generating Image Embeddings via Textual Summarisation.txt', '.txt', 12048, false),
('Generate SEO Seed Keywords Using AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Generate SEO Seed Keywords Using AI.txt', '.txt', 9009, false),
('dealer_lead_qualifier.json', '/Users/tushar/Desktop/N8N-Agents/n8n/dealer_lead_qualifier.json', '.json', 5989, false),
('breaking_news_summarizer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/breaking_news_summarizer.json', '.json', 6013, false),
('Sentiment Analysis Tracking on Support Issues with Linear and Slack (1).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Sentiment Analysis Tracking on Support Issues with Linear and Slack (1).txt', '.txt', 17943, false),
('Summarize your emails with A.I. (via Openrouter) and send to Line messenger.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Summarize your emails with A.I. (via Openrouter) and send to Line messenger.txt', '.txt', 4976, false),
('OpenAI assistant with custom tools.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/OpenAI assistant with custom tools.txt', '.txt', 7905, false),
('Translate audio using AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Translate audio using AI.txt', '.txt', 7430, false),
('🔍 Perplexity Research to HTML_ AI-Powered Content Creation.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/🔍 Perplexity Research to HTML_ AI-Powered Content Creation.txt', '.txt', 141476, false),
('pr_merged_qa_notify.json', '/Users/tushar/Desktop/N8N-Agents/n8n/pr_merged_qa_notify.json', '.json', 7856, false),
('neighborhood_safety_insights.json', '/Users/tushar/Desktop/N8N-Agents/n8n/neighborhood_safety_insights.json', '.json', 6018, false),
('mqtt_topic_monitor.json', '/Users/tushar/Desktop/N8N-Agents/n8n/mqtt_topic_monitor.json', '.json', 5947, false),
('soil_nutrient_analysis.json', '/Users/tushar/Desktop/N8N-Agents/n8n/soil_nutrient_analysis.json', '.json', 6005, false),
('edge_device_log_compressor.json', '/Users/tushar/Desktop/N8N-Agents/n8n/edge_device_log_compressor.json', '.json', 5997, false),
('Enrich Pipedrive_s Organization Data with OpenAI GPT-4o & Notify it in Slack.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Enrich Pipedrive_s Organization Data with OpenAI GPT-4o & Notify it in Slack.txt', '.txt', 10543, false),
('🤖 Telegram Messaging Agent for Text_Audio_Images.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/🤖 Telegram Messaging Agent for Text_Audio_Images.txt', '.txt', 21189, false),
('Compose reply draft in Gmail with OpenAI Assistant.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Compose reply draft in Gmail with OpenAI Assistant.txt', '.txt', 11780, false),
('Automated AI image analysis and response via Telegram.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automated AI image analysis and response via Telegram.txt', '.txt', 7706, false),
('Recipe Recommendations with Qdrant and Mistral.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Recipe Recommendations with Qdrant and Mistral.txt', '.txt', 22221, false),
('fitness_api_weekly_report.json', '/Users/tushar/Desktop/N8N-Agents/n8n/fitness_api_weekly_report.json', '.json', 7634, false),
('industrial_iot_kpi_email.json', '/Users/tushar/Desktop/N8N-Agents/n8n/industrial_iot_kpi_email.json', '.json', 5975, false),
('Enrich FAQ sections on your website pages at scale with AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Enrich FAQ sections on your website pages at scale with AI.txt', '.txt', 32816, false),
('Prompt-based Object Detection with Gemini 2.0.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Prompt-based Object Detection with Gemini 2.0.txt', '.txt', 11417, false),
('auto_reply_to_faqs.json', '/Users/tushar/Desktop/N8N-Agents/n8n/auto_reply_to_faqs.json', '.json', 7732, false),
('script_dialogue_analyzer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/script_dialogue_analyzer.json', '.json', 6013, false),
('Extract Information from a Logo Sheet using forms, AI, Google Sheet and Airtable.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Extract Information from a Logo Sheet using forms, AI, Google Sheet and Airtable.txt', '.txt', 36511, false),
('voice_note_transcription.json', '/Users/tushar/Desktop/N8N-Agents/n8n/voice_note_transcription.json', '.json', 7494, false),
('twitch_clip_highlights_script.json', '/Users/tushar/Desktop/N8N-Agents/n8n/twitch_clip_highlights_script.json', '.json', 6029, false),
('onboarding_checklist_slack.json', '/Users/tushar/Desktop/N8N-Agents/n8n/onboarding_checklist_slack.json', '.json', 7659, false),
('drink_water_reminder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/drink_water_reminder.json', '.json', 7593, false),
('cross-post_youtube_uploads_to_facebook.json', '/Users/tushar/Desktop/N8N-Agents/n8n/cross-post_youtube_uploads_to_facebook.json', '.json', 7936, false),
('AI-Powered Children_s English Storytelling on Telegram with OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI-Powered Children_s English Storytelling on Telegram with OpenAI.txt', '.txt', 10879, false),
('interview_scheduler.json', '/Users/tushar/Desktop/N8N-Agents/n8n/interview_scheduler.json', '.json', 7584, false),
('Enhance Customer Chat by Buffering Messages with Twilio and Redis.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Enhance Customer Chat by Buffering Messages with Twilio and Redis.txt', '.txt', 10234, false),
('Vector Database as a Big Data Analysis Tool for AI Agents [2_2 KNN] (1).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Vector Database as a Big Data Analysis Tool for AI Agents [2_2 KNN] (1).txt', '.txt', 13098, false),
('AI-Powered Information Monitoring with OpenAI, Google Sheets, Jina AI and Slack.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI-Powered Information Monitoring with OpenAI, Google Sheets, Jina AI and Slack.txt', '.txt', 34644, false),
('AI Youtube Trend Finder Based On Niche.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Youtube Trend Finder Based On Niche.txt', '.txt', 11743, false),
('Ultimate Scraper Workflow for n8n.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Ultimate Scraper Workflow for n8n.txt', '.txt', 41103, false),
('Build an OpenAI Assistant with Google Drive Integration.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Build an OpenAI Assistant with Google Drive Integration.txt', '.txt', 6641, false),
('flight_price_drop_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/flight_price_drop_alert.json', '.json', 5999, false),
('survey_auto_analyze.json', '/Users/tushar/Desktop/N8N-Agents/n8n/survey_auto_analyze.json', '.json', 7860, false),
('case_law_summarizer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/case_law_summarizer.json', '.json', 5977, false),
('Handling Appointment Leads and Follow-up With Twilio, Cal.com and AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Handling Appointment Leads and Follow-up With Twilio, Cal.com and AI.txt', '.txt', 44094, false),
('Transcribe Audio Files, Summarize with GPT-4, and Store in Notion.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Transcribe Audio Files, Summarize with GPT-4, and Store in Notion.txt', '.txt', 6106, false),
('LINE Assistant with Google Calendar and Gmail Integration.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/LINE Assistant with Google Calendar and Gmail Integration.txt', '.txt', 10496, false),
('Query Perplexity AI from your n8n workflows.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Query Perplexity AI from your n8n workflows.txt', '.txt', 3890, false),
('README.md', '/Users/tushar/Desktop/N8N-Agents/n8n/README.md', '.md', 879, false),
('local_attraction_recommender.json', '/Users/tushar/Desktop/N8N-Agents/n8n/local_attraction_recommender.json', '.json', 6034, false),
('unpaid_invoice_reminder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/unpaid_invoice_reminder.json', '.json', 7486, false),
('blog_comment_discord.json', '/Users/tushar/Desktop/N8N-Agents/n8n/blog_comment_discord.json', '.json', 7601, false),
('pest_outbreak_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/pest_outbreak_alert.json', '.json', 5977, false),
('habit_form_weekly_summary.json', '/Users/tushar/Desktop/N8N-Agents/n8n/habit_form_weekly_summary.json', '.json', 7638, false),
('crop_yield_predictor.json', '/Users/tushar/Desktop/N8N-Agents/n8n/crop_yield_predictor.json', '.json', 5993, false),
('quality_defect_classifier.json', '/Users/tushar/Desktop/N8N-Agents/n8n/quality_defect_classifier.json', '.json', 5992, false),
('energy_consumption_anomaly_detector.json', '/Users/tushar/Desktop/N8N-Agents/n8n/energy_consumption_anomaly_detector.json', '.json', 6070, false),
('disaster_api_sms.json', '/Users/tushar/Desktop/N8N-Agents/n8n/disaster_api_sms.json', '.json', 7565, false),
('ga_report_email.json', '/Users/tushar/Desktop/N8N-Agents/n8n/ga_report_email.json', '.json', 7816, false),
('Customer Insights with Qdrant, Python and Information Extractor.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Customer Insights with Qdrant, Python and Information Extractor.txt', '.txt', 27743, false),
('greenhouse_climate_controller.json', '/Users/tushar/Desktop/N8N-Agents/n8n/greenhouse_climate_controller.json', '.json', 6040, false),
('Summarize Umami data with AI (via Openrouter) and save it to Baserow.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Summarize Umami data with AI (via Openrouter) and save it to Baserow.txt', '.txt', 11904, false),
('Build Your Own Image Search Using AI Object Detection, CDN and ElasticSearchBuild Your Own Image Search Using AI Object Detection, CDN and ElasticSearch.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Build Your Own Image Search Using AI Object Detection, CDN and ElasticSearchBuild Your Own Image Search Using AI Object Detection, CDN and ElasticSearch.txt', '.txt', 10684, false),
('Auto-label incoming Gmail messages with AI nodes.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Auto-label incoming Gmail messages with AI nodes.txt', '.txt', 9484, false),
('Proxmox AI Agent with n8n and Generative AI Integration.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Proxmox AI Agent with n8n and Generative AI Integration.txt', '.txt', 28989, false),
('Hacker News to Video Content.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Hacker News to Video Content.txt', '.txt', 30092, false),
('OpenAI examples_ ChatGPT, DALLE-2, Whisper-1 – 5-in-1.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/OpenAI examples_ ChatGPT, DALLE-2, Whisper-1 – 5-in-1.txt', '.txt', 15320, false),
('Organise Your Local File Directories With AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Organise Your Local File Directories With AI.txt', '.txt', 10485, false),
('Chat with local LLMs using n8n and Ollama.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Chat with local LLMs using n8n and Ollama.txt', '.txt', 2970, false),
('Send Google analytics data to A.I. to analyze then save results in BaserowSend Google analytics data to A.I. to analyze then save results in Baserow.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Send Google analytics data to A.I. to analyze then save results in BaserowSend Google analytics data to A.I. to analyze then save results in Baserow.txt', '.txt', 24195, false),
('⚡AI-Powered YouTube Video Summarization & Analysis.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/⚡AI-Powered YouTube Video Summarization & Analysis.txt', '.txt', 6488, false),
('Hacker News Job Listing Scraper and Parser.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Hacker News Job Listing Scraper and Parser.txt', '.txt', 18506, false),
('Vector Database as a Big Data Analysis Tool for AI Agents [3_3 - anomaly].txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Vector Database as a Big Data Analysis Tool for AI Agents [3_3 - anomaly].txt', '.txt', 12452, false),
('parse_invoice_emails.json', '/Users/tushar/Desktop/N8N-Agents/n8n/parse_invoice_emails.json', '.json', 7478, false),
('hourly_weather_log.json', '/Users/tushar/Desktop/N8N-Agents/n8n/hourly_weather_log.json', '.json', 7845, false),
('new_job_application_parser.json', '/Users/tushar/Desktop/N8N-Agents/n8n/new_job_application_parser.json', '.json', 7937, false),
('low_stock_discord.json', '/Users/tushar/Desktop/N8N-Agents/n8n/low_stock_discord.json', '.json', 7850, false),
('Flux AI Image Generator.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Flux AI Image Generator.txt', '.txt', 17915, false),
('Remove Personally Identifiable Information (PII) from CSV Files with OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Remove Personally Identifiable Information (PII) from CSV Files with OpenAI.txt', '.txt', 7748, false),
('AI Agent for project management and meetings with Airtable and Fireflies.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Agent for project management and meetings with Airtable and Fireflies.txt', '.txt', 14513, false),
('HR Job Posting and Evaluation with AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/HR Job Posting and Evaluation with AI.txt', '.txt', 62111, false),
('Telegram Bot with Supabase memory and OpenAI assistant integration.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Telegram Bot with Supabase memory and OpenAI assistant integration.txt', '.txt', 25732, false),
('daily_student_motivation.json', '/Users/tushar/Desktop/N8N-Agents/n8n/daily_student_motivation.json', '.json', 7629, false),
('Reddit AI digest.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Reddit AI digest.txt', '.txt', 8880, false),
('court_date_reminder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/court_date_reminder.json', '.json', 5977, false),
('stripe_to_quickbooks.json', '/Users/tushar/Desktop/N8N-Agents/n8n/stripe_to_quickbooks.json', '.json', 7466, false),
('Optimize & Update Printify Title and Description Workflow.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Optimize & Update Printify Title and Description Workflow.txt', '.txt', 22300, false),
('ride‑share_surge_predictor.json', '/Users/tushar/Desktop/N8N-Agents/n8n/ride‑share_surge_predictor.json', '.json', 6049, false),
('github_commit_jenkins.json', '/Users/tushar/Desktop/N8N-Agents/n8n/github_commit_jenkins.json', '.json', 7602, false),
('schedule_instagram_content_from_airtable.json', '/Users/tushar/Desktop/N8N-Agents/n8n/schedule_instagram_content_from_airtable.json', '.json', 7956, false),
('Send specific PDF attachments from Gmail to Google Drive using OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Send specific PDF attachments from Gmail to Google Drive using OpenAI.txt', '.txt', 9479, false),
('voice_task_to_notion.json', '/Users/tushar/Desktop/N8N-Agents/n8n/voice_task_to_notion.json', '.json', 7593, false),
('Speed Up Social Media Banners With BannerBear.com.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Speed Up Social Media Banners With BannerBear.com.txt', '.txt', 11358, false),
('vin_decoder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/vin_decoder.json', '.json', 5923, false),
('Bitrix24 Chatbot Application Workflow example with Webhook Integration.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Bitrix24 Chatbot Application Workflow example with Webhook Integration.txt', '.txt', 15956, false),
('🔐🦙🤖 Private & Local Ollama Self-Hosted AI Assistant.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/🔐🦙🤖 Private & Local Ollama Self-Hosted AI Assistant.txt', '.txt', 8206, false),
('competitor_price_scraper.json', '/Users/tushar/Desktop/N8N-Agents/n8n/competitor_price_scraper.json', '.json', 7641, false),
('ALL_unique_nodes.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/ALL_unique_nodes.txt', '.txt', 0, false),
('Visual Regression Testing with Apify and AI Vision Model.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Visual Regression Testing with Apify and AI Vision Model.txt', '.txt', 23496, false),
('public_record_email_update.json', '/Users/tushar/Desktop/N8N-Agents/n8n/public_record_email_update.json', '.json', 7933, false),
('inventory_slack_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/inventory_slack_alert.json', '.json', 7878, false),
('Generate 9_16 Images from Content and Brand Guidelines.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Generate 9_16 Images from Content and Brand Guidelines.txt', '.txt', 43027, false),
('fuel_price_monitor.json', '/Users/tushar/Desktop/N8N-Agents/n8n/fuel_price_monitor.json', '.json', 5995, false),
('renewable_incentive_tracker.json', '/Users/tushar/Desktop/N8N-Agents/n8n/renewable_incentive_tracker.json', '.json', 6040, false),
('podcast_transcribe_publish.json', '/Users/tushar/Desktop/N8N-Agents/n8n/podcast_transcribe_publish.json', '.json', 7945, false),
('summarize_customer_emails.json', '/Users/tushar/Desktop/N8N-Agents/n8n/summarize_customer_emails.json', '.json', 7514, false),
('autonomous_vehicle_log_summarizer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/autonomous_vehicle_log_summarizer.json', '.json', 6058, false),
('Convert text to speech with OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Convert text to speech with OpenAI.txt', '.txt', 4005, false),
('Email Subscription Service with n8n Forms, Airtable and AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Email Subscription Service with n8n Forms, Airtable and AI.txt', '.txt', 28842, false),
('Creating a AI Slack Bot with Google Gemini.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Creating a AI Slack Bot with Google Gemini.txt', '.txt', 5077, false),
('api_monitor_auto_restart.json', '/Users/tushar/Desktop/N8N-Agents/n8n/api_monitor_auto_restart.json', '.json', 7629, false),
('Enhance Security Operations with the Qualys Slack Shortcut Bot!.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Enhance Security Operations with the Qualys Slack Shortcut Bot!.txt', '.txt', 23948, false),
('Telegram AI bot with LangChain nodes.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Telegram AI bot with LangChain nodes.txt', '.txt', 8592, false),
('virtual_economy_price_tracker.json', '/Users/tushar/Desktop/N8N-Agents/n8n/virtual_economy_price_tracker.json', '.json', 6029, false),
('Email Subscription Service with n8n Forms, Airtable and AI (1).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Email Subscription Service with n8n Forms, Airtable and AI (1).txt', '.txt', 28842, false),
('AI Agent to chat with Supabase_PostgreSQL DB.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Agent to chat with Supabase_PostgreSQL DB.txt', '.txt', 7548, false),
('Telegram to Spotify with OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Telegram to Spotify with OpenAI.txt', '.txt', 7742, false),
('Agentic Telegram AI bot with with LangChain nodes and new tools.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Agentic Telegram AI bot with with LangChain nodes and new tools.txt', '.txt', 4894, false),
('AI agent that can scrape webpages.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI agent that can scrape webpages.txt', '.txt', 11723, false),
('zoom_attendance_log.json', '/Users/tushar/Desktop/N8N-Agents/n8n/zoom_attendance_log.json', '.json', 7596, false),
('Basic Automatic Gmail Email Labelling with OpenAI and Gmail API.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Basic Automatic Gmail Email Labelling with OpenAI and Gmail API.txt', '.txt', 10475, false),
('🤖🧑_💻 AI Agent for Top n8n Creators Leaderboard Reporting.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/🤖🧑_💻 AI Agent for Top n8n Creators Leaderboard Reporting.txt', '.txt', 26823, false),
('social_buzz_heatmap.json', '/Users/tushar/Desktop/N8N-Agents/n8n/social_buzz_heatmap.json', '.json', 5979, false),
('patent_abstract_summarizer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/patent_abstract_summarizer.json', '.json', 6012, false),
('wind_farm_maintenance_scheduler.json', '/Users/tushar/Desktop/N8N-Agents/n8n/wind_farm_maintenance_scheduler.json', '.json', 6048, false),
('Actioning Your Meeting Next Steps using Transcripts and AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Actioning Your Meeting Next Steps using Transcripts and AI.txt', '.txt', 18436, false),
('sensor_fault_detector.json', '/Users/tushar/Desktop/N8N-Agents/n8n/sensor_fault_detector.json', '.json', 5989, false),
('Extract spending history from gmail to google sheet.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Extract spending history from gmail to google sheet.txt', '.txt', 25813, false),
('Scrape and summarize webpages with AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Scrape and summarize webpages with AI.txt', '.txt', 5989, false),
('Handling Job Application Submissions with AI and n8n Forms.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Handling Job Application Submissions with AI and n8n Forms.txt', '.txt', 27018, false),
('visa_requirement_checker.json', '/Users/tushar/Desktop/N8N-Agents/n8n/visa_requirement_checker.json', '.json', 6014, false),
('solar_output_forecaster.json', '/Users/tushar/Desktop/N8N-Agents/n8n/solar_output_forecaster.json', '.json', 6020, false),
('Transcribing Bank Statements To Markdown Using Gemini Vision AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Transcribing Bank Statements To Markdown Using Gemini Vision AI.txt', '.txt', 13303, false),
('Automate Pinterest Analysis & AI-Powered Content Suggestions With Pinterest API.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automate Pinterest Analysis & AI-Powered Content Suggestions With Pinterest API.txt', '.txt', 11073, false),
('ticket_urgency_classification.json', '/Users/tushar/Desktop/N8N-Agents/n8n/ticket_urgency_classification.json', '.json', 7842, false),
('Analyze & Sort Suspicious Email Contents with ChatGPT.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Analyze & Sort Suspicious Email Contents with ChatGPT.txt', '.txt', 19769, false),
('Daily Podcast Summary.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Daily Podcast Summary.txt', '.txt', 13164, false),
('Generate SQL queries from schema only - AI-powered.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Generate SQL queries from schema only - AI-powered.txt', '.txt', 16702, false),
('Hacker News Throwback Machine - See What Was Hot on This Day, Every Year!.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Hacker News Throwback Machine - See What Was Hot on This Day, Every Year!.txt', '.txt', 8379, false),
('server_health_grafana.json', '/Users/tushar/Desktop/N8N-Agents/n8n/server_health_grafana.json', '.json', 7610, false),
('Obsidian Notes Read Aloud using AI_ Available as a Podcast Feed.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Obsidian Notes Read Aloud using AI_ Available as a Podcast Feed.txt', '.txt', 19744, false),
('safety_incident_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/safety_incident_alert.json', '.json', 5973, false),
('🎨 Interactive Image Editor with FLUX.1 Fill Tool for Inpainting.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/🎨 Interactive Image Editor with FLUX.1 Fill Tool for Inpainting.txt', '.txt', 13001, false),
('Venafi Cloud Slack Cert Bot.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Venafi Cloud Slack Cert Bot.txt', '.txt', 39701, false),
('AI_ Summarize podcast episode and enhance using Wikipedia.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI_ Summarize podcast episode and enhance using Wikipedia.txt', '.txt', 38201, false),
('reddit_upvote_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/reddit_upvote_alert.json', '.json', 7470, false),
('HR & IT Helpdesk Chatbot with Audio Transcription.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/HR & IT Helpdesk Chatbot with Audio Transcription.txt', '.txt', 16203, false),
('📚 Auto-generate documentation for n8n workflows with GPT and Docsify.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/📚 Auto-generate documentation for n8n workflows with GPT and Docsify.txt', '.txt', 45737, false),
('return_ticket_assignment.json', '/Users/tushar/Desktop/N8N-Agents/n8n/return_ticket_assignment.json', '.json', 7625, false),
('player_sentiment_dashboard.json', '/Users/tushar/Desktop/N8N-Agents/n8n/player_sentiment_dashboard.json', '.json', 6035, false),
('Translate Telegram audio messages with AI (55 supported languages).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Translate Telegram audio messages with AI (55 supported languages).txt', '.txt', 7111, false),
('Auto-Tag Blog Posts in WordPress with AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Auto-Tag Blog Posts in WordPress with AI.txt', '.txt', 16721, false),
('Building Your First WhatsApp Chatbot.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Building Your First WhatsApp Chatbot.txt', '.txt', 16598, false),
('issue_trello_card.json', '/Users/tushar/Desktop/N8N-Agents/n8n/issue_trello_card.json', '.json', 7574, false),
('fleet_fuel_efficiency_report.json', '/Users/tushar/Desktop/N8N-Agents/n8n/fleet_fuel_efficiency_report.json', '.json', 6045, false),
('AI-powered WooCommerce Support-Agent.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI-powered WooCommerce Support-Agent.txt', '.txt', 25852, false),
('travel_itinerary_builder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/travel_itinerary_builder.json', '.json', 6002, false),
('Extract text from PDF and image using Vertex AI (Gemini) into CSV.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Extract text from PDF and image using Vertex AI (Gemini) into CSV.txt', '.txt', 10236, false),
('Enrich Property Inventory Survey with Image Recognition and AI Agent.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Enrich Property Inventory Survey with Image Recognition and AI Agent.txt', '.txt', 21638, false),
('packaging_waste_calculator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/packaging_waste_calculator.json', '.json', 5997, false),
('property_description_generator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/property_description_generator.json', '.json', 6045, false),
('gdpr_violation_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/gdpr_violation_alert.json', '.json', 5984, false),
('AI Crew to Automate Fundamental Stock Analysis - Q&A Workflow.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Crew to Automate Fundamental Stock Analysis - Q&A Workflow.txt', '.txt', 7668, false),
('travel_advisory_monitor.json', '/Users/tushar/Desktop/N8N-Agents/n8n/travel_advisory_monitor.json', '.json', 6009, false),
('🐋🤖 DeepSeek AI Agent + Telegram + LONG TERM Memory 🧠.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/🐋🤖 DeepSeek AI Agent + Telegram + LONG TERM Memory 🧠.txt', '.txt', 16986, false),
('📈 Receive Daily Market News from FT.com to your Microsoft outlook inbox.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/📈 Receive Daily Market News from FT.com to your Microsoft outlook inbox.txt', '.txt', 7289, false),
('record_crypto_prices.json', '/Users/tushar/Desktop/N8N-Agents/n8n/record_crypto_prices.json', '.json', 7474, false),
('esports_match_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/esports_match_alert.json', '.json', 5988, false),
('woo_order_mailchimp.json', '/Users/tushar/Desktop/N8N-Agents/n8n/woo_order_mailchimp.json', '.json', 7580, false),
('Complete business WhatsApp AI-Powered RAG Chatbot using OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Complete business WhatsApp AI-Powered RAG Chatbot using OpenAI.txt', '.txt', 15334, false),
('patch_note_summarizer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/patch_note_summarizer.json', '.json', 5989, false),
('keyword_rank_checker.json', '/Users/tushar/Desktop/N8N-Agents/n8n/keyword_rank_checker.json', '.json', 7867, false),
('Classify lemlist replies using OpenAI and automate reply handling.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Classify lemlist replies using OpenAI and automate reply handling.txt', '.txt', 10840, false),
('Send daily translated Calvin and Hobbes Comics to Discord.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Send daily translated Calvin and Hobbes Comics to Discord.txt', '.txt', 5806, false),
('AI Social Media Caption Creator creates social media post captions in Airtable.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Social Media Caption Creator creates social media post captions in Airtable.txt', '.txt', 21382, false),
('CV Resume PDF Parsing with Multimodal Vision AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/CV Resume PDF Parsing with Multimodal Vision AI.txt', '.txt', 8721, false),
('🐋DeepSeek V3 Chat & R1 Reasoning Quick Start.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/🐋DeepSeek V3 Chat & R1 Reasoning Quick Start.txt', '.txt', 7566, false),
('Automate Sales Meeting Prep with AI & APIFY Sent To WhatsApp.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automate Sales Meeting Prep with AI & APIFY Sent To WhatsApp.txt', '.txt', 43242, false),
('bank_sms_alert_to_telegram.json', '/Users/tushar/Desktop/N8N-Agents/n8n/bank_sms_alert_to_telegram.json', '.json', 7526, false),
('auto_archive_promotions.json', '/Users/tushar/Desktop/N8N-Agents/n8n/auto_archive_promotions.json', '.json', 7774, false),
('privacy_policy_generator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/privacy_policy_generator.json', '.json', 5987, false),
('RAG Chatbot for Company Documents using Google Drive and Gemini.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/RAG Chatbot for Company Documents using Google Drive and Gemini.txt', '.txt', 10484, false),
('crm_patient_intake.json', '/Users/tushar/Desktop/N8N-Agents/n8n/crm_patient_intake.json', '.json', 7587, false),
('Summarize YouTube Videos from Transcript.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Summarize YouTube Videos from Transcript.txt', '.txt', 4277, false),
('alert_on_instagram_competitor_story.json', '/Users/tushar/Desktop/N8N-Agents/n8n/alert_on_instagram_competitor_story.json', '.json', 7586, false),
('Survey Insights with Qdrant, Python and Information Extractor.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Survey Insights with Qdrant, Python and Information Extractor.txt', '.txt', 29256, false),
('Vector Database as a Big Data Analysis Tool for AI Agents [2_3 - anomaly].txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Vector Database as a Big Data Analysis Tool for AI Agents [2_3 - anomaly].txt', '.txt', 34969, false),
('Share YouTube Videos with AI Summaries on Discord.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Share YouTube Videos with AI Summaries on Discord.txt', '.txt', 5214, false),
('contract_clause_extractor.json', '/Users/tushar/Desktop/N8N-Agents/n8n/contract_clause_extractor.json', '.json', 6007, false),
('AI web researcher for sales.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI web researcher for sales.txt', '.txt', 20242, false),
('maintenance_ticket_router.json', '/Users/tushar/Desktop/N8N-Agents/n8n/maintenance_ticket_router.json', '.json', 6009, false),
('Visualize your SQL Agent queries with OpenAI and Quickchart.io.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Visualize your SQL Agent queries with OpenAI and Quickchart.io.txt', '.txt', 19685, false),
('youtube_transcript_to_blog.json', '/Users/tushar/Desktop/N8N-Agents/n8n/youtube_transcript_to_blog.json', '.json', 7949, false),
('auto-tag_blog_posts.json', '/Users/tushar/Desktop/N8N-Agents/n8n/auto-tag_blog_posts.json', '.json', 7470, false),
('weekly_shopify_sales_summary.json', '/Users/tushar/Desktop/N8N-Agents/n8n/weekly_shopify_sales_summary.json', '.json', 7832, false),
('rss_headlines_slack.json', '/Users/tushar/Desktop/N8N-Agents/n8n/rss_headlines_slack.json', '.json', 7856, false),
('Notion AI Assistant Generator.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Notion AI Assistant Generator.txt', '.txt', 25747, false),
('legal_billing_analyzer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/legal_billing_analyzer.json', '.json', 5977, false),
('Enhance Security Operations with the Qualys Slack Shortcut Bot! (1).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Enhance Security Operations with the Qualys Slack Shortcut Bot! (1).txt', '.txt', 23948, false),
('nda_risk_detector.json', '/Users/tushar/Desktop/N8N-Agents/n8n/nda_risk_detector.json', '.json', 5951, false),
('Chat with OpenAI Assistant (by adding a memory).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Chat with OpenAI Assistant (by adding a memory).txt', '.txt', 5818, false),
('AI-powered email processing autoresponder and response approval (Yes_No).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI-powered email processing autoresponder and response approval (Yes_No).txt', '.txt', 9829, false),
('shopify_order_sms.json', '/Users/tushar/Desktop/N8N-Agents/n8n/shopify_order_sms.json', '.json', 7846, false),
('farm_equipment_maintenance_reminder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/farm_equipment_maintenance_reminder.json', '.json', 6059, false),
('starred_slack_to_notion.json', '/Users/tushar/Desktop/N8N-Agents/n8n/starred_slack_to_notion.json', '.json', 7616, false),
('AI Data Extraction with Dynamic Prompts and Airtable.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Data Extraction with Dynamic Prompts and Airtable.txt', '.txt', 35914, false),
('Image Creation with OpenAI and Telegram.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Image Creation with OpenAI and Telegram.txt', '.txt', 6120, false),
('AI Data Extraction with Dynamic Prompts and Baserow.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Data Extraction with Dynamic Prompts and Baserow.txt', '.txt', 28924, false),
('OpenAI Assistant workflow_ upload file, create an Assistant, chat with it!.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/OpenAI Assistant workflow_ upload file, create an Assistant, chat with it!.txt', '.txt', 6014, false),
('mes_log_analyzer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/mes_log_analyzer.json', '.json', 5973, false),
('AI Voice Chatbot with ElevenLabs & OpenAI for Customer Service and Restaurants.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Voice Chatbot with ElevenLabs & OpenAI for Customer Service and Restaurants.txt', '.txt', 12021, false),
('zoning_regulation_checker.json', '/Users/tushar/Desktop/N8N-Agents/n8n/zoning_regulation_checker.json', '.json', 5982, false),
('vehicle_telematics_analyzer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/vehicle_telematics_analyzer.json', '.json', 5992, false),
('Automate Customer Support Issue Resolution using AI Text Classifier.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automate Customer Support Issue Resolution using AI Text Classifier.txt', '.txt', 28228, false),
('Parse PDF with LlamaParse and save to Airtable.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Parse PDF with LlamaParse and save to Airtable.txt', '.txt', 14962, false),
('Spot Workplace Discrimination Patterns with AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Spot Workplace Discrimination Patterns with AI.txt', '.txt', 59976, false),
('hotel_review_sentiment.json', '/Users/tushar/Desktop/N8N-Agents/n8n/hotel_review_sentiment.json', '.json', 6005, false),
('Turn Emails into AI-Enhanced Tasks in Notion (Multi-User Support) with Gmail, Airtable and Softr.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Turn Emails into AI-Enhanced Tasks in Notion (Multi-User Support) with Gmail, Airtable and Softr.txt', '.txt', 25382, false),
('AI Fitness Coach Strava Data Analysis and Personalized Training Insights.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Fitness Coach Strava Data Analysis and Personalized Training Insights.txt', '.txt', 16542, false),
('✨ Vision-Based AI Agent Scraper - with Google Sheets, ScrapingBee, and Gemini.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/✨ Vision-Based AI Agent Scraper - with Google Sheets, ScrapingBee, and Gemini.txt', '.txt', 21118, false),
('Ask a human for help when the AI doesn_t know the answer.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Ask a human for help when the AI doesn_t know the answer.txt', '.txt', 7094, false),
('shift_handover_summary.json', '/Users/tushar/Desktop/N8N-Agents/n8n/shift_handover_summary.json', '.json', 6005, false),
('Introduction to the HTTP Tool.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Introduction to the HTTP Tool.txt', '.txt', 6565, false),
('hoa_fee_analyzer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/hoa_fee_analyzer.json', '.json', 5985, false),
('Slack slash commands AI Chat Bot.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Slack slash commands AI Chat Bot.txt', '.txt', 6166, false),
('ev_battery_degradation_report.json', '/Users/tushar/Desktop/N8N-Agents/n8n/ev_battery_degradation_report.json', '.json', 6000, false),
('resume_screening.json', '/Users/tushar/Desktop/N8N-Agents/n8n/resume_screening.json', '.json', 7430, false),
('Create a Google Analytics Data Report with AI and sent it to E-Mail and Telegram.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Create a Google Analytics Data Report with AI and sent it to E-Mail and Telegram.txt', '.txt', 14971, false),
('paypal_to_airtable.json', '/Users/tushar/Desktop/N8N-Agents/n8n/paypal_to_airtable.json', '.json', 7450, false),
('Chat Assistant (OpenAI assistant) with Postgres Memory And API Calling Capabalities.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Chat Assistant (OpenAI assistant) with Postgres Memory And API Calling Capabalities.txt', '.txt', 9881, false),
('BambooHR AI-Powered Company Policies and Benefits Chatbot.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/BambooHR AI-Powered Company Policies and Benefits Chatbot.txt', '.txt', 26693, false),
('Narrating over a Video using Multimodal AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Narrating over a Video using Multimodal AI.txt', '.txt', 15883, false),
('Angie, Personal AI Assistant with Telegram Voice and Text.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Angie, Personal AI Assistant with Telegram Voice and Text.txt', '.txt', 8535, false),
('Use OpenRouter in n8n versions _1.78.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Use OpenRouter in n8n versions _1.78.txt', '.txt', 3797, false),
('AI-Driven Lead Management and Inquiry Automation with ERPNext & n8n.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI-Driven Lead Management and Inquiry Automation with ERPNext & n8n.txt', '.txt', 21457, false),
('Building Your First WhatsApp Chatbot (1).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Building Your First WhatsApp Chatbot (1).txt', '.txt', 16598, false),
('Extract data from resume and create PDF with Gotenberg.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Extract data from resume and create PDF with Gotenberg.txt', '.txt', 25038, false),
('adas_event_annotator.json', '/Users/tushar/Desktop/N8N-Agents/n8n/adas_event_annotator.json', '.json', 5982, false),
('course_completion_certificate.json', '/Users/tushar/Desktop/N8N-Agents/n8n/course_completion_certificate.json', '.json', 7674, false),
('Automate Competitor Research with Exa.ai, Notion and AI Agents.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Automate Competitor Research with Exa.ai, Notion and AI Agents.txt', '.txt', 36620, false),
('MongoDB AI Agent - Intelligent Movie Recommendations.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/MongoDB AI Agent - Intelligent Movie Recommendations.txt', '.txt', 5427, false),
('medication_sms_reminder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/medication_sms_reminder.json', '.json', 7628, false),
('discord_guild_welcome_bot.json', '/Users/tushar/Desktop/N8N-Agents/n8n/discord_guild_welcome_bot.json', '.json', 6009, false),
('connected_car_alert.json', '/Users/tushar/Desktop/N8N-Agents/n8n/connected_car_alert.json', '.json', 5950, false),
('AI agent chat.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI agent chat.txt', '.txt', 1945, false),
('Invoice data extraction with LlamaParse and OpenAI (1).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Invoice data extraction with LlamaParse and OpenAI (1).txt', '.txt', 22067, false),
('Generate audio from text using OpenAI and Webhook _ Text to Speech Workflow.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Generate audio from text using OpenAI and Webhook _ Text to Speech Workflow.txt', '.txt', 2905, false),
('Manipulate PDF with Adobe developer API.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Manipulate PDF with Adobe developer API.txt', '.txt', 12624, false),
('smart_home_energy_saver.json', '/Users/tushar/Desktop/N8N-Agents/n8n/smart_home_energy_saver.json', '.json', 5999, false),
('Qualifying Appointment Requests with AI & n8n Forms.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Qualifying Appointment Requests with AI & n8n Forms.txt', '.txt', 20266, false),
('Text automations using Apple Shortcuts (1).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Text automations using Apple Shortcuts (1).txt', '.txt', 10110, false),
('trademark_status_monitor.json', '/Users/tushar/Desktop/N8N-Agents/n8n/trademark_status_monitor.json', '.json', 6015, false),
('A Very Simple _Human in the Loop_ Email Response System Using AI and IMAP.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/A Very Simple _Human in the Loop_ Email Response System Using AI and IMAP.txt', '.txt', 8171, false),
('inventory_restock_forecast.json', '/Users/tushar/Desktop/N8N-Agents/n8n/inventory_restock_forecast.json', '.json', 6024, false),
('appointment_whatsapp_notify.json', '/Users/tushar/Desktop/N8N-Agents/n8n/appointment_whatsapp_notify.json', '.json', 7656, false),
('currency_rate_monitor.json', '/Users/tushar/Desktop/N8N-Agents/n8n/currency_rate_monitor.json', '.json', 7474, false),
('Get Airtable data via AI and Obsidian Notes.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Get Airtable data via AI and Obsidian Notes.txt', '.txt', 4220, false),
('etsy_review_to_slack.json', '/Users/tushar/Desktop/N8N-Agents/n8n/etsy_review_to_slack.json', '.json', 7593, false),
('unsplash_to_pinterest.json', '/Users/tushar/Desktop/N8N-Agents/n8n/unsplash_to_pinterest.json', '.json', 7598, false),
('🚀 Local Multi-LLM Testing & Performance Tracker.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/🚀 Local Multi-LLM Testing & Performance Tracker.txt', '.txt', 19227, false),
('Social Media Analysis and Automated Email Generation.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Social Media Analysis and Automated Email Generation.txt', '.txt', 17853, false),
('Learn Anything from HN - Get Top Resource Recommendations from Hacker News.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Learn Anything from HN - Get Top Resource Recommendations from Hacker News.txt', '.txt', 6486, false),
('Dynamically generate a webpage from user request using OpenAI Structured Output (1).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Dynamically generate a webpage from user request using OpenAI Structured Output (1).txt', '.txt', 7929, false),
('Discord AI-powered bot.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Discord AI-powered bot.txt', '.txt', 5273, false),
('daily_email_digest.json', '/Users/tushar/Desktop/N8N-Agents/n8n/daily_email_digest.json', '.json', 7462, false),
('Fetch Dynamic Prompts from GitHub and Auto-Populate n8n Expressions in Prompt.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Fetch Dynamic Prompts from GitHub and Auto-Populate n8n Expressions in Prompt.txt', '.txt', 9656, false),
('ChatGPT Automatic Code Review in Gitlab MR.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/ChatGPT Automatic Code Review in Gitlab MR.txt', '.txt', 8444, false),
('Post New YouTube Videos to X.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Post New YouTube Videos to X.txt', '.txt', 3414, false),
('real_estate_market_trend_report.json', '/Users/tushar/Desktop/N8N-Agents/n8n/real_estate_market_trend_report.json', '.json', 6049, false),
('AI-Powered Children_s Arabic Storytelling on Telegram.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI-Powered Children_s Arabic Storytelling on Telegram.txt', '.txt', 10992, false),
('tv_rating_trend_report.json', '/Users/tushar/Desktop/N8N-Agents/n8n/tv_rating_trend_report.json', '.json', 5978, false),
('Advanced AI Demo (Presented at AI Developers #14 meetup).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Advanced AI Demo (Presented at AI Developers #14 meetup).txt', '.txt', 18988, false),
('Summarize the New Documents from Google Drive and Save Summary in Google Sheet.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Summarize the New Documents from Google Drive and Save Summary in Google Sheet.txt', '.txt', 7030, false),
('json_to_sheet.json', '/Users/tushar/Desktop/N8N-Agents/n8n/json_to_sheet.json', '.json', 7794, false),
('production_kpi_dashboard.json', '/Users/tushar/Desktop/N8N-Agents/n8n/production_kpi_dashboard.json', '.json', 6002, false),
('Intelligent Web Query and Semantic Re-Ranking Flow using Brave and Google Gemini.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Intelligent Web Query and Semantic Re-Ranking Flow using Brave and Google Gemini.txt', '.txt', 35424, false),
('AI chat with any data source (using the n8n workflow tool).txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI chat with any data source (using the n8n workflow tool).txt', '.txt', 4736, false),
('weather_impact_report.json', '/Users/tushar/Desktop/N8N-Agents/n8n/weather_impact_report.json', '.json', 6010, false),
('Integrating AI with Open-Meteo API for Enhanced Weather Forecasting.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Integrating AI with Open-Meteo API for Enhanced Weather Forecasting.txt', '.txt', 8418, false),
('Host Your Own AI Deep Research Agent with n8n, Apify and OpenAI o3.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Host Your Own AI Deep Research Agent with n8n, Apify and OpenAI o3.txt', '.txt', 150314, false),
('AI Agent to chat with you Search Console Data, using OpenAI and Postgres.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Agent to chat with you Search Console Data, using OpenAI and Postgres.txt', '.txt', 24138, false),
('Extract personal data with self-hosted LLM Mistral NeMo.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Extract personal data with self-hosted LLM Mistral NeMo.txt', '.txt', 6489, false),
('Telegram AI Chatbot.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Telegram AI Chatbot.txt', '.txt', 8622, false),
('UTM Link Creator & QR Code Generator with Scheduled Google Analytics Reports.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/UTM Link Creator & QR Code Generator with Scheduled Google Analytics Reports.txt', '.txt', 10084, false),
('Auto-Categorize blog posts in wordpress using A.I..txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Auto-Categorize blog posts in wordpress using A.I..txt', '.txt', 4773, false),
('Classify new bugs in Linear with OpenAI_s GPT-4 and move them to the right team.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Classify new bugs in Linear with OpenAI_s GPT-4 and move them to the right team.txt', '.txt', 17220, false),
('vAssistant for Hubspot Chat using OpenAi and Airtable.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/vAssistant for Hubspot Chat using OpenAi and Airtable.txt', '.txt', 22013, false),
('Qualify new leads in Google Sheets via OpenAI_s GPT-4.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Qualify new leads in Google Sheets via OpenAI_s GPT-4.txt', '.txt', 8560, false),
('youtube_comment_summarizer.json', '/Users/tushar/Desktop/N8N-Agents/n8n/youtube_comment_summarizer.json', '.json', 7804, false),
('Microsoft Outlook AI Email Assistant with contact support from Monday and Airtable.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Microsoft Outlook AI Email Assistant with contact support from Monday and Airtable.txt', '.txt', 20747, false),
('supply_chain_delay_monitor.json', '/Users/tushar/Desktop/N8N-Agents/n8n/supply_chain_delay_monitor.json', '.json', 6012, false),
('🔥📈🤖 AI Agent for n8n Creators Leaderboard - Find Popular Workflows.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/🔥📈🤖 AI Agent for n8n Creators Leaderboard - Find Popular Workflows.txt', '.txt', 27674, false),
('Deduplicate Scraping AI Grants for Eligibility using AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Deduplicate Scraping AI Grants for Eligibility using AI.txt', '.txt', 35090, false),
('auto-reply_to_tiktok_comments.json', '/Users/tushar/Desktop/N8N-Agents/n8n/auto-reply_to_tiktok_comments.json', '.json', 7842, false),
('AI Powered Web Scraping with Jina, Google Sheets and OpenAI _ the EASY way.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Powered Web Scraping with Jina, Google Sheets and OpenAI _ the EASY way.txt', '.txt', 5365, false),
('API Schema Extractor.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/API Schema Extractor.txt', '.txt', 73443, false),
('AI Agent with Ollama for current weather and wiki.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/AI Agent with Ollama for current weather and wiki.txt', '.txt', 4335, false),
('Auto Categorise Outlook Emails with AI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Auto Categorise Outlook Emails with AI.txt', '.txt', 26364, false),
('achievement_suggestion_engine.json', '/Users/tushar/Desktop/N8N-Agents/n8n/achievement_suggestion_engine.json', '.json', 6040, false),
('Scrape Trustpilot Reviews with DeepSeek, Analyze Sentiment with OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Scrape Trustpilot Reviews with DeepSeek, Analyze Sentiment with OpenAI.txt', '.txt', 16333, false),
('Upsert huge documents in a vector store with Supabase and Notion.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Upsert huge documents in a vector store with Supabase and Notion.txt', '.txt', 15045, false),
('assignment_sms_reminder.json', '/Users/tushar/Desktop/N8N-Agents/n8n/assignment_sms_reminder.json', '.json', 7616, false),
('Reconcile Rent Payments with Local Excel Spreadsheet and OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Reconcile Rent Payments with Local Excel Spreadsheet and OpenAI.txt', '.txt', 13037, false),
('harvest_logbook.json', '/Users/tushar/Desktop/N8N-Agents/n8n/harvest_logbook.json', '.json', 5959, false),
('Store Notion_s Pages as Vector Documents into Supabase with OpenAI.txt', '/Users/tushar/Desktop/N8N-Agents/n8n/Store Notion_s Pages as Vector Documents into Supabase with OpenAI.txt', '.txt', 6920, false),
('notion_job_board_poster.json', '/Users/tushar/Desktop/N8N-Agents/n8n/notion_job_board_poster.json', '.json', 7620, false);